import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StaffProvider } from "@/lib/utils/StaffProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SMILE MEMORIES",
  description: "Generated by create next app",
  manifest:"/manifest.json"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StaffProvider>
          {children}
        </StaffProvider>
      </body>
    </html>
  );
}
